### ISSUE TITLE
cs120_lab2_linear_regression_df.py - randomSplit changed result in Databrick may cause inconsistent test cases

### ISSUE THREAD

**Issue by micksatana** [spark-mooc/mooc-setup#20]
Some change in Databrick caused randomSplit to result differently since yesterday (02/08/2016).

The same test case was correct yesterday but when I ran again today I found these test cases became incorrect due to result changed of randomSplit in <a href="https://github.com/spark-mooc/mooc-setup/blob/master/cs120_lab2_linear_regression_df.py#L352">line 352</a>

https://github.com/spark-mooc/mooc-setup/blob/master/cs120_lab2_linear_regression_df.py#L384
should be
`Test.assertEquals(round(float(n_train) / float(n_train + n_val + n_test), 1), .8, 'unexpected value for nTrain')`

https://github.com/spark-mooc/mooc-setup/blob/master/cs120_lab2_linear_regression_df.py#L385
should be
`Test.assertEquals(round(float(n_val) / float(n_train + n_val + n_test), 1), .1, 'unexpected value for nVal')
`

https://github.com/spark-mooc/mooc-setup/blob/master/cs120_lab2_linear_regression_df.py#L386
should be
`Test.assertEquals(round(float(n_test) / float(n_train + n_val + n_test), 1), .1, 'unexpected value for nTest')
`

**Comment by brett--anderson** [comment]
Adding to this, I'm trying to complete the archived course on edx. I'm getting n_train: 5405, n_val: 644, n_test: 675

All prior tests in the lab are passing. I've read through the piazza discussion, and though a similar problem was reported [here](https://piazza.com/class/iqfbu516yuj5t3?cid=174), none of the suggestions have helped. I've also tried rewriting my answers to prior sections in numerous ways and I still end up with the same partitioning. 

The suggested fix might get the test in question to pass, but subsequent tests which check averages in each set fail and presumably much of the rest of the lab will have mismatched results.

Perhaps this should be changed to something that isn't actually random, some previously saved random set of indexes that can be loaded from a txt file or something?

**Comment by micksatana** [comment]
It's been a long time since I posted this issue. I can't really remember what it is now.

In general, I quite agree with Brett on test cases shouldn't be random. But if, for whatever reason, the test needed to have random value, then all the subsequest tests should also be fixed. Or maybe re-design the lab ;)

Anyway, I'll close this issue. It seems the course owner is not interested enough to fix it.
