### ISSUE TITLE
Minor typos/grammar errors in ML_lab3_linear_reg_student.ipynb

### ISSUE THREAD

**Issue by colgur** [spark-mooc/mooc-setup#7]
Three changes for your consideration where underscores are insertions and dashes are strike throughs:
- line 361: 'task involves split_ting_ it into training, validation and test sets' 
- line 490: 'Calculates the -the- squared error'
- line 815: 'gradient` s_h_ould be a '

**Comment by jonbates** [comment]
Thanks for these.  I've  made the changes in our master notebook.
